openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths: {}
components:
  schemas:
    User:
      $ref: "https://raw.githubusercontent.com/YOUR-GITHUB-USERNAME/component-repo/main/schemas/User.yaml"
